// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agwrpqazamehouwebupq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnd3JwcWF6YW1laG91d2VidXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzQ5MjcsImV4cCI6MjA2NDgxMDkyN30.v_MmucYtjqzvRy-35jaS8GIevfEF3hAdFXdjK21Ujbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);